
name: Simple c++ Build
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - run: gcc hello-world.c
    - run : ./a.out
